<template>
  <section class="page-head"><div><p class="eyebrow">Auditoria do código real</p><h1>Limites e contratos da API</h1><p>Itens implementados e ausências documentadas sem criar comportamentos fictícios.</p></div></section>
  <section class="notes-grid">
    <article class="panel"><h2>Autenticação implementada</h2><ul><li><code>POST /api/auth/login</code> autentica por e-mail e senha.</li><li><code>GET /api/auth/me</code> recupera o usuário autenticado com perfil.</li><li><code>POST /api/auth/logout</code> revoga o token atual.</li><li>Rotas privadas usam token Bearer do Sanctum.</li></ul></article>
    <article class="panel"><h2>Área do usuário</h2><ul><li><code>GET /api/me/vehicles</code> lista veículos vinculados.</li><li><code>POST /api/me/vehicles</code> vincula veículo com placa e tipo.</li><li><code>GET /api/me/stays</code> lista permanências dos veículos do usuário.</li><li><code>GET /api/me/charges</code> lista cobranças vinculadas ao usuário.</li><li><code>POST /api/me/charges/{charge}/pay</code> paga cobrança da própria conta.</li></ul></article>
    <article class="panel"><h2>Área administrativa</h2><ul><li>Rotas administrativas estão protegidas por perfil <code>admin</code>.</li><li>Admin gerencia usuários, veículos, zonas, permanências e cobranças pelos contratos existentes.</li><li>Menus administrativos só aparecem quando a API retorna <code>role: admin</code>.</li></ul></article>
    <article class="panel"><h2>Ausências confirmadas</h2><ul><li>Não há endpoint de cadastro público.</li><li>Não há endpoints para depósito ou consulta direta de carteira fora do perfil.</li><li>Não há endpoints para listar ou pagar multas.</li><li>Não há CRUD completo implementado para zonas além das rotas registradas.</li><li>O Swagger salvo diverge das rotas e validações atuais.</li></ul></article>
  </section>
</template>
